stages:
  - deploy

deploy:
  image: python:3.6
  stage: deploy
  tags:
    - aws
    - docker
  before_script:
    - pip install awscli -q
  script:
    - aws s3 sync ./public s3://$S3_BUCKET_NAME/ --delete --acl public-read
    - aws cloudfront create-invalidation --distribution-id ${AWS_DISTRIBUTION_ID} --paths "/*"
  only:
    - master
